spring.application.name=registration

spring.datasource.url=jdbc:oracle:thin:@nombre_de_tu_bd_tp?TNS_ADMIN=C:/ruta/a/tu/Wallet_DB
spring.datasource.username=TU_USUARIO_DE_BASE_DE_DATOS
spring.datasource.password=TU_CONTRASEÑA
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Configuración de JPA/Hibernate para crear tablas automáticamente y ver el SQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
